### ISSUE TITLE
Not Works :(

### ISSUE THREAD

**Issue by maitret** [jakejarvis/backblaze-b2-action#1]
Using https://api.backblazeb2.com

 count: 0 files   compare: 0 files   updated: 0 files   0 B   0 B/s

Traceback (most recent call last):
  File "/usr/local/bin/b2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/b2/console_tool.py", line 1485, in main
    exit_status = ct.run_command(decoded_argv)
  File "/usr/local/lib/python3.7/site-packages/b2/console_tool.py", line 1361, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.7/site-packages/b2/console_tool.py", line 1184, in run
    allow_empty_source=allow_empty_source
  File "/usr/local/lib/python3.7/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.7/site-packages/b2sdk/sync/sync.py", line 259, in sync_folders
    raise ValueError('neither folder is a b2 folder')

ValueError: neither folder is a b2 folder

**Comment by maitret** [comment]
[https://github.com/maitret/file/blob/master/.github/workflows/main.yml](https://github.com/maitret/file/blob/master/.github/workflows/main.yml)

name: Sync B2 Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/backblaze-b2-action@master

      env:
        SOURCE_DIR: '/'
        B2_BUCKET: ${{ secrets.B2_BUCKET }}
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}

**Comment by alydevs** [comment]
The usage of the b2 cli tool has changed, it looks like setting B2_BUCKET to `b2://bucket-name/path/` will work, this is the new path convention as indicated in `b2 sync --help`

    One of the paths must be a local file path, and the other must be
    a B2 bucket path. Use "b2://<bucketName>/<prefix>" for B2 paths, e.g.
    "b2://my-bucket-name/a/path/prefix/".

**Comment by TigerHix** [comment]
> The usage of the b2 cli tool has changed, it looks like setting B2_BUCKET to `b2://bucket-name/path/` will work, this is the new path convention as indicated in `b2 sync --help`
> 
> ```
> One of the paths must be a local file path, and the other must be
> a B2 bucket path. Use "b2://<bucketName>/<prefix>" for B2 paths, e.g.
> "b2://my-bucket-name/a/path/prefix/".
> ```

Can confirm this works. Thanks!
